modules_dir = "artifacts/"
total_memory_limit = "Infinity"

[[module]]
    name = "sqlite3"
    mem_pages_count = 100
    logger_enabled = false

[[module]]
    name = "test"
    mem_pages_count = 1
    logger_enabled = false
