name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  tests:
    name: "sqlite-wasm"
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}

  snapshot:
    name: "sqlite-wasm"
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}
