name: Run tests with workflow call

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "master"

jobs:
  tests:
    name: "cargo test"
    runs-on: builder
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/sqlite-wasm-connector
          ref: ${{ inputs.ref }}

      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: sqlite-wasm-connector
          save-if: false

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1
        with:
          artifact-name: marine

      - name: Download sqlite-wasm
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: sqlite-wasm
          path: artifacts/

      - name: Build
        run: ./build.sh

      - name: Run cargo test
        run: cargo test --release --all-features

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      # - name: Run cargo clippy
      #   run: cargo clippy --all --all-features
