name: Run tests
on:
  workflow_call:
    inputs:
      ref:
        description: "git ref to checkout to"
        type: string
        default: "master"

jobs:
  tests:
    name: "cargo test"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/sqlite-wasm-connector
          ref: ${{ inputs.ref }}

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Download marine artifact
        id: marine
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: marine
          path: ~/.local/bin

      - name: Make marine executable
        if: steps.marine.outcome == 'success'
        run: chmod +x ${{ steps.marine.outputs.download-path }}

      - name: Setup marine
        if: steps.marine.outcome == 'failure'
        uses: fluencelabs/setup-marine@v1

      - name: Download sqlite-wasm
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: sqlite-wasm
          path: artifacts/

      - name: Build
        run: ./build.sh

      - name: Run cargo test
        run: cargo test --release --all-features

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      # - name: Run cargo clippy
      #   run: cargo clippy --all --all-features
